### ISSUE TITLE
How it's work ?

### ISSUE THREAD

**Issue by MpLLLL71** [innc11/QuickShopX#3]
Hi! How create a shop ?

It doesn't work like QuickShop... :/

**Comment by asforest** [comment]
My English is not very good. It works similar to QuickShop on Bukkit. First, click the chest with the left button (win10), or hold down with your finger for about 0.5s, but don't break it(android / ios), then enter the price in the chatbar. If you want to modify the price, click the sign on the chest or use the command of this plugin. BTW, If there are some items that cannot be created normally, please create them empty-handed and then switch to the items before entering the price

**Comment by MpLLLL71** [comment]
Thank you I will try.

Can you release 1.5.2 ?

**Comment by MpLLLL71** [comment]
`00:26:08 [FATAL] Could not pass event "cn.nukkit.event.player.PlayerInteractEvent" to "QuickShopX v1.5.1": null on cn.innc11.quickshopx.listener.CreateShopListener
> 00:26:08 [ERROR] Throwing
cn.nukkit.utils.EventException: null
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:34) ~[server.jar:?]
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56) ~[server.jar:?]
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546) ~[server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2423) ~[server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) ~[?:?]
at java.util.ArrayList.forEach(ArrayList.java:1257) [?:1.8.0_242]
at cn.nukkit.network.Network.processPackets(Network.java:197) [server.jar:?]
at cn.nukkit.network.Network.processBatch(Network.java:180) [server.jar:?]
at cn.nukkit.Player.handleDataPacket(Player.java:2099) [server.jar:?]
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source) [GAC-1.0.jar:?]
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157) [server.jar:?]
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132) [server.jar:?]
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68) [server.jar:?]
at cn.nukkit.network.Network.processInterfaces(Network.java:83) [server.jar:?]
at cn.nukkit.Server.tick(Server.java:1132) [server.jar:?]
at cn.nukkit.Server.tickProcessor(Server.java:911) [server.jar:?]
at cn.nukkit.Server.start(Server.java:888) [server.jar:?]
at cn.nukkit.Server.<init>(Server.java:573) [server.jar:?]
at cn.nukkit.Nukkit.main(Nukkit.java:112) [server.jar:?]
Caused by: java.lang.NullPointerException
at cn.innc11.quickshopx.listener.CreateShopListener.createShop(CreateShopListener.java:87) ~[?:?]
at cn.innc11.quickshopx.listener.CreateShopListener.onPlayerInteract(CreateShopListener.java:157) ~[?:?]
at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_242]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_242]
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29) ~[server.jar:?]
... 18 more
> java.lang.NoSuchFieldException: perm
at java.lang.Class.getDeclaredField(Class.java:2070)
at cn.innc11.quickshopx.listener.CreateShopListener.createShop(CreateShopListener.java:78)
at cn.innc11.quickshopx.listener.CreateShopListener.onPlayerInteract(CreateShopListener.java:157)
at sun.reflect.GeneratedMethodAccessor79.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at cn.nukkit.plugin.MethodEventExecutor.execute(MethodEventExecutor.java:29)
at cn.nukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:56)
at cn.nukkit.plugin.PluginManager.callEvent(PluginManager.java:546)
at cn.nukkit.Player.handleDataPacket(Player.java:2423)
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at cn.nukkit.network.Network.processPackets(Network.java:197)
at cn.nukkit.network.Network.processBatch(Network.java:180)
at cn.nukkit.Player.handleDataPacket(Player.java:2099)
at cz.creeperface.nukkit.gac.player.NukkitCheatPlayer.handleDataPacket(Unknown Source)
at cn.nukkit.network.RakNetInterface.handleEncapsulated(RakNetInterface.java:157)
at cn.nukkit.raknet.server.ServerHandler.handlePacket(ServerHandler.java:132)
at cn.nukkit.network.RakNetInterface.process(RakNetInterface.java:68)
at cn.nukkit.network.Network.processInterfaces(Network.java:83)
at cn.nukkit.Server.tick(Server.java:1132)
at cn.nukkit.Server.tickProcessor(Server.java:911)
at cn.nukkit.Server.start(Server.java:888)
at cn.nukkit.Server.<init>(Server.java:573)
at cn.nukkit.Nukkit.main(Nukkit.java:112)`

**Comment by asforest** [comment]
oh, due to permission issues, I forgot to say that 1.5.2 and 1.5.1 cannot be used with the GAC plugin, I will fix it in the next version, before that, you can use v1.5

**Comment by MpLLLL71** [comment]
Thank you very much for your answer!
